"""add question type

Revision ID: 26ef95fc6f2c
Revises: 2335f2c85292
Create Date: 2015-03-30 13:20:33.312616

"""

# revision identifiers, used by Alembic.
revision = '26ef95fc6f2c'
down_revision = '2335f2c85292'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    question_types = op.create_table('question_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### Populate with question types
    op.bulk_insert(question_types,
        [
            {'name':'standard'},
            {'name':'image'}
        ]
    )
    op.add_column(u'question', sa.Column('question_type_id', sa.Integer(), nullable=False, server_default="1"))
    op.create_foreign_key('fk_quesion_question_types', 'question', 'question_types', ['question_type_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_quesion_question_types', 'question', type_='foreignkey')
    op.drop_column(u'question', 'question_type_id')
    op.drop_table('question_types')
    ### end Alembic commands ###
