"""add finished writing

Revision ID: 2a26731bd08e
Revises: 2fe1ed8ce31c
Create Date: 2015-04-08 16:03:50.934405

"""

# revision identifiers, used by Alembic.
revision = '2a26731bd08e'
down_revision = '2fe1ed8ce31c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finished_writing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='fk_finished_writing_question', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_finished_writing_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Add multi column constraint
    op.create_unique_constraint("uq_finished_writing_1", "finished_writing", ["user_id", "question_id", "generation"])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finished_writing')
    ### end Alembic commands ###
