"""add voting type

Revision ID: 2fe1ed8ce31c
Revises: 320f4eb0698b
Create Date: 2015-04-04 11:48:15.440410

"""

# revision identifiers, used by Alembic.
revision = '2fe1ed8ce31c'
down_revision = '320f4eb0698b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    voting_types = op.create_table('voting_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### Populate with question types
    op.bulk_insert(voting_types,
        [
            {'name':'triangle'},
            {'name':'linear'}
        ]
    )
    op.add_column(u'question', sa.Column('voting_type_id', sa.Integer(), nullable=False, server_default="1"))
    op.create_foreign_key('fk_quesion_voting_types', 'question', 'voting_types', ['voting_type_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_quesion_voting_types', 'question', type_='foreignkey')
    op.drop_column(u'question', 'voting_type_id')
    op.drop_table('voting_types')
    ### end Alembic commands ###
