"""add proposal image

Revision ID: 320f4eb0698b
Revises: 26ef95fc6f2c
Create Date: 2015-03-31 15:55:20.062624

"""

# revision identifiers, used by Alembic.
revision = '320f4eb0698b'
down_revision = '26ef95fc6f2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('image', sa.String(length=150), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'image')
    ### end Alembic commands ###
